import parameters
import constants
import random

## ------------------------------------------------------------------------------------------------
## The code for quicksort and insertion sort was generated by ChatGPT as it was permitted for this lab
##------------------------------------------------------------------------------------------------

##------------------------------------------------------------------------------------------------
## Initialization of the samples array
samples = []
##------------------------------------------------------------------------------------------------

##------------------------------------------------------------------------------------------------
## Function to access all the samples and put them in an array
def access_files():
    for i in range(0, parameters.nb_samples):
        file_name = f'samples/sample_{parameters.array_size}_{parameters.magnitude}_{i+1}.txt'
        with open(file_name, 'r') as file:
            samples.append(file.read())
            file.close()
##------------------------------------------------------------------------------------------------

##------------------------------------------------------------------------------------------------
## Counting sort
def counting_sort(original_array: list, size: int) -> list:
    max_element = max(original_array)
    count_array = [0] * (max_element + 1)
    for element in original_array:
        count_array[element] += 1

    for i in range(1, len(count_array)):
        count_array[i] += count_array[i - 1]

    output = [0] * size

    for element in original_array:
        correct_position = count_array[element] - 1
        output[correct_position] = element
        count_array[element] -= 1  # Decrease count of current element

    return output
##------------------------------------------------------------------------------------------------

##------------------------------------------------------------------------------------------------
## Insertion Sort used in the quicksort algorithm
def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
    return arr
##------------------------------------------------------------------------------------------------

##------------------------------------------------------------------------------------------------
## Quicksort with a recursion threshold of 1 and with the pivot being the first element of the array
def quicksort_first_first(arr):
    if len(arr) <= constants.THRESHOLD_ONE:
        # Use insertion sort for small subarrays
        return insertion_sort(arr)

    pivot = arr[0]
    lesser = []
    greater = []

    for element in arr[1:]:
        if element < pivot:
            lesser.append(element)
        else:
            greater.append(element)

    return quicksort_first_first(lesser) + [pivot] + quicksort_first_first(greater)
##------------------------------------------------------------------------------------------------

##------------------------------------------------------------------------------------------------
## Quicksort with a recursion threshold of 12 and with the pivot being the first element of the array
def quicksort_experimental_first(arr):
    if len(arr) <= constants.THRESHOLD_EXPERIMENTAL_FIRST:
        # Use insertion sort for small subarrays
        return insertion_sort(arr)

    pivot = arr[0]
    lesser = []
    greater = []

    for element in arr[1:]:
        if element < pivot:
            lesser.append(element)
        else:
            greater.append(element)

    return quicksort_experimental_first(lesser) + [pivot] + quicksort_experimental_first(greater)
##------------------------------------------------------------------------------------------------

##------------------------------------------------------------------------------------------------
## Quicksort with a recursion threshold of 19 and with the pivot being generated randomly each time
def quicksort_experimental_random(arr):
    if len(arr) <= constants.THRESHOLD_EXPERIMENTAL_RANDOM:
        # Use insertion sort for small subarrays
        return insertion_sort(arr)
    # Random index generated here
    random_index = random.randint(0, len(arr)-1)
    pivot = arr[random_index]
    lesser = []
    greater = []

    for element in arr[1:]:
        if element < pivot:
            lesser.append(element)
        else:
            greater.append(element)

    return quicksort_experimental_random(lesser) + [pivot] + quicksort_experimental_random(greater)
##------------------------------------------------------------------------------------------------